apiVersion: v1
kind: Service
metadata:
  name: student-app-service
  namespace: devops
spec:
  type: NodePort
  selector:
    app: student-app-final
  ports:
  - port: 8080
    targetPort: 8080
    nodePort: 30080
